# Generated by Django 4.2.20 on 2025-03-26 15:30

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PokCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('user_id', models.IntegerField(help_text='User ID associated with the certificate')),
                ('course_id', models.CharField(help_text='Course ID associated with the certificate', max_length=255)),
                ('certificate_id', models.CharField(blank=True, help_text='Certificate ID in the Open edX platform', max_length=255, null=True)),
                ('pok_certificate_url', models.URLField(blank=True, help_text='URL to the POK certificate page', max_length=255, null=True)),
                ('pok_response', models.TextField(blank=True, help_text='Full response from POK API', null=True)),
                ('is_valid', models.BooleanField(default=False, help_text='Whether the POK certificate is valid')),
            ],
            options={
                'unique_together': {('user_id', 'course_id')},
            },
        ),
    ]
