# Generated by Django 4.2.20 on 2025-04-30 16:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0029_alter_historicalcourseoverview_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('openedx_pok_webhook', '0006_coursetemplate_api_key'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseTemplate',
            new_name='CertificateTemplate',
        ),
        migrations.RenameModel(
            old_name='CertificatePokApi',
            new_name='PokCertificate',
        ),
    ]
